### ISSUE TITLE
Проблема с запуском в kubernetes

### ISSUE THREAD

**Issue by howard180** [arkuznetsov/hirac#2]
При запуске образа в k8s (версия 1.20, рантайм containerd) возникает проблема: 

```
Unhandled exception. ScriptEngine.Compiler.SymbolNotFoundException: {Модуль /app/model/modules/ПодключенияКАгентам.os / Ошибка в строке: 34,37 / Неизвестный символ: ТипыОбъектовКластера}
        ПоляОбъекта = ТипыОбъектовКластера.СвойстваОбъекта(ТипОбъекта);

```

проблема возникает при инициализации пода, то есть под (контейнер) падает.

**Comment by arkuznetsov** [comment]
А библиотека irac установлена в каталоге oscript_modules?

**Comment by howard180** [comment]
Да, это первое, что я проверил: наличие модуля "ТипыОбъектовКластера.os". 
Вообще, в Docker все запускается нормально (немного правда подшаманил с созданием образа и entrypoint поменял), а вот в k8s какая-то беда.

**Comment by howard180** [comment]
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[3]
      Hosting starting
ScriptEngine.Compiler.SymbolNotFoundException: {Модуль /app/model/modules/ПодключенияКАгентам.os / Ошибка в строке: 34,37 / Неизвестный символ: ТипыОбъектовКластера}
        ПоляОбъекта = ТипыОбъектовКластера.СвойстваОбъекта(ТипОбъекта);
   at ScriptEngine.Compiler.CompilerContext.GetSymbol(String symbol, Func`2 extract)
   at ScriptEngine.Compiler.CompilerContext.GetVariable(String name)
   at ScriptEngine.Compiler.ModuleCompilerContext.GetVariable(String name)
   at ScriptEngine.Compiler.Compiler.BuildPushVariable(String identifier)
   at ScriptEngine.Compiler.Compiler.ProcessPrimaryIdentifier()
   at ScriptEngine.Compiler.Compiler.BuildPrimaryNode()
   at ScriptEngine.Compiler.Compiler.BuildExpression(Token stopToken)
   at ScriptEngine.Compiler.Compiler.BuildSimpleStatement()
   at ScriptEngine.Compiler.Compiler.BuildCodeBatch(Token[] endTokens)
   at ScriptEngine.Compiler.Compiler.DispatchMethodBody()
   at ScriptEngine.Compiler.Compiler.BuildSingleMethod()
   at ScriptEngine.Compiler.Compiler.DispatchModuleBuild()
   at ScriptEngine.Compiler.Compiler.BuildModule()
   at ScriptEngine.Compiler.Compiler.Compile(ILexemGenerator lexer, ICompilerContext context)
   at ScriptEngine.CompilerService.CompileInternal(ICodeSource source)
   at ScriptEngine.CompilerService.Compile(ICodeSource source)
   at ScriptEngine.Machine.Contexts.AttachedScriptsFactory.CompileModuleFromSource(CompilerService compiler, ICodeSource code, ExternalContextData externalContext)
   at ScriptEngine.HostedScript.LibraryLoader.CompileFile(String path)
   at ScriptEngine.HostedScript.LibraryLoader.<CompileDelayedModules>b__28_0(UserAddedScript moduleFile)
   at ScriptEngine.Utils.ForEach[T](IEnumerable`1 input, Action`1 action)
   at ScriptEngine.HostedScript.LibraryLoader.CompileDelayedModules(ExternalLibraryDef library)
   at ScriptEngine.HostedScript.LibraryLoader.ProcessLibrary(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.ProcessLibrary(Library lib)
   at ScriptEngine.HostedScript.LibraryResolver.LoadLibraryInternal(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.LoadByPath(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.LoadByRelativePath(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.LoadLibrary(String value)
   at ScriptEngine.HostedScript.LibraryResolver.Resolve(String directive, String value, Boolean codeEntered)
   at ScriptEngine.Compiler.DirectiveMultiResolver.Resolve(String directive, String value, Boolean codeEntered)
   at ScriptEngine.CompilerService.ResolveDirective(String directive, String value, Boolean codeEntered)
   at ScriptEngine.Compiler.Compiler.HandleDirective()
   at ScriptEngine.Compiler.Compiler.HandleImportDirectives()
   at ScriptEngine.Compiler.Compiler.DispatchModuleBuild()
   at ScriptEngine.Compiler.Compiler.BuildModule()
   at ScriptEngine.Compiler.Compiler.Compile(ILexemGenerator lexer, ICompilerContext context)
   at ScriptEngine.CompilerService.CompileInternal(ICodeSource source)
   at ScriptEngine.CompilerService.Compile(ICodeSource source)
   at OneScript.WebHost.Application.ApplicationInstance.Create(ICodeSource src, IApplicationRuntime webApp) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Application/ApplicationInstance.cs:line 264
   at OneScript.WebHost.Infrastructure.AppStarter.CreateApp() in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Infrastructure/AppStarter.cs:line 72
   at OneScript.WebHost.Infrastructure.OneScriptServicePlugin.<>c.<InitializeScriptedLayer>b__4_0(IServiceProvider sp) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Infrastructure/OneScriptServicePlugin.cs:line 80
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OneScript.WebHost.Startup.StartOneScriptApp(IApplicationBuilder app, IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 108
Application startup exception: ScriptEngine.Compiler.SymbolNotFoundException: {Модуль /app/model/modules/ПодключенияКАгентам.os / Ошибка в строке: 34,37 / Неизвестный символ: ТипыОбъектовКластера}
        ПоляОбъекта = ТипыОбъектовКластера.СвойстваОбъекта(ТипОбъекта);
   at ScriptEngine.Compiler.CompilerContext.GetSymbol(String symbol, Func`2 extract)
   at ScriptEngine.Compiler.CompilerContext.GetVariable(String name)
   at ScriptEngine.Compiler.ModuleCompilerContext.GetVariable(String name)
   at ScriptEngine.Compiler.Compiler.BuildPushVariable(String identifier)
   at ScriptEngine.Compiler.Compiler.ProcessPrimaryIdentifier()
   at ScriptEngine.Compiler.Compiler.BuildPrimaryNode()
   at ScriptEngine.Compiler.Compiler.BuildExpression(Token stopToken)
   at ScriptEngine.Compiler.Compiler.BuildSimpleStatement()
   at ScriptEngine.Compiler.Compiler.BuildCodeBatch(Token[] endTokens)
   at ScriptEngine.Compiler.Compiler.DispatchMethodBody()
   at ScriptEngine.Compiler.Compiler.BuildSingleMethod()
   at ScriptEngine.Compiler.Compiler.DispatchModuleBuild()
   at ScriptEngine.Compiler.Compiler.BuildModule()
   at ScriptEngine.Compiler.Compiler.Compile(ILexemGenerator lexer, ICompilerContext context)
   at ScriptEngine.CompilerService.CompileInternal(ICodeSource source)
   at ScriptEngine.CompilerService.Compile(ICodeSource source)
   at ScriptEngine.Machine.Contexts.AttachedScriptsFactory.CompileModuleFromSource(CompilerService compiler, ICodeSource code, ExternalContextData externalContext)
   at ScriptEngine.HostedScript.LibraryLoader.CompileFile(String path)
   at ScriptEngine.HostedScript.LibraryLoader.<CompileDelayedModules>b__28_0(UserAddedScript moduleFile)
   at ScriptEngine.Utils.ForEach[T](IEnumerable`1 input, Action`1 action)
   at ScriptEngine.HostedScript.LibraryLoader.CompileDelayedModules(ExternalLibraryDef library)
   at ScriptEngine.HostedScript.LibraryLoader.ProcessLibrary(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.ProcessLibrary(Library lib)
   at ScriptEngine.HostedScript.LibraryResolver.LoadLibraryInternal(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.LoadByPath(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.LoadByRelativePath(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.LoadLibrary(String value)
   at ScriptEngine.HostedScript.LibraryResolver.Resolve(String directive, String value, Boolean codeEntered)
   at ScriptEngine.Compiler.DirectiveMultiResolver.Resolve(String directive, String value, Boolean codeEntered)
   at ScriptEngine.CompilerService.ResolveDirective(String directive, String value, Boolean codeEntered)
   at ScriptEngine.Compiler.Compiler.HandleDirective()
   at ScriptEngine.Compiler.Compiler.HandleImportDirectives()
   at ScriptEngine.Compiler.Compiler.DispatchModuleBuild()
   at ScriptEngine.Compiler.Compiler.BuildModule()
   at ScriptEngine.Compiler.Compiler.Compile(ILexemGenerator lexer, ICompilerContext context)
   at ScriptEngine.CompilerService.CompileInternal(ICodeSource source)
   at ScriptEngine.CompilerService.Compile(ICodeSource source)
   at OneScript.WebHost.Application.ApplicationInstance.Create(ICodeSource src, IApplicationRuntime webApp) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Application/ApplicationInstance.cs:line 264
   at OneScript.WebHost.Infrastructure.AppStarter.CreateApp() in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Infrastructure/AppStarter.cs:line 72
   at OneScript.WebHost.Infrastructure.OneScriptServicePlugin.<>c.<InitializeScriptedLayer>b__4_0(IServiceProvider sp) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Infrastructure/OneScriptServicePlugin.cs:line 80
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OneScript.WebHost.Startup.StartOneScriptApp(IApplicationBuilder app, IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 108
   at OneScript.WebHost.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 98
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.WebHost[6]
      Application startup exception
ScriptEngine.Compiler.SymbolNotFoundException: {Модуль /app/model/modules/ПодключенияКАгентам.os / Ошибка в строке: 34,37 / Неизвестный символ: ТипыОбъектовКластера}
        ПоляОбъекта = ТипыОбъектовКластера.СвойстваОбъекта(ТипОбъекта);
   at ScriptEngine.Compiler.CompilerContext.GetSymbol(String symbol, Func`2 extract)
   at ScriptEngine.Compiler.CompilerContext.GetVariable(String name)
   at ScriptEngine.Compiler.ModuleCompilerContext.GetVariable(String name)
   at ScriptEngine.Compiler.Compiler.BuildPushVariable(String identifier)
   at ScriptEngine.Compiler.Compiler.ProcessPrimaryIdentifier()
   at ScriptEngine.Compiler.Compiler.BuildPrimaryNode()
   at ScriptEngine.Compiler.Compiler.BuildExpression(Token stopToken)
   at ScriptEngine.Compiler.Compiler.BuildSimpleStatement()
   at ScriptEngine.Compiler.Compiler.BuildCodeBatch(Token[] endTokens)
   at ScriptEngine.Compiler.Compiler.DispatchMethodBody()
   at ScriptEngine.Compiler.Compiler.BuildSingleMethod()
   at ScriptEngine.Compiler.Compiler.DispatchModuleBuild()
   at ScriptEngine.Compiler.Compiler.BuildModule()
   at ScriptEngine.Compiler.Compiler.Compile(ILexemGenerator lexer, ICompilerContext context)
   at ScriptEngine.CompilerService.CompileInternal(ICodeSource source)
   at ScriptEngine.CompilerService.Compile(ICodeSource source)
   at ScriptEngine.Machine.Contexts.AttachedScriptsFactory.CompileModuleFromSource(CompilerService compiler, ICodeSource code, ExternalContextData externalContext)
   at ScriptEngine.HostedScript.LibraryLoader.CompileFile(String path)
   at ScriptEngine.HostedScript.LibraryLoader.<CompileDelayedModules>b__28_0(UserAddedScript moduleFile)
   at ScriptEngine.Utils.ForEach[T](IEnumerable`1 input, Action`1 action)
   at ScriptEngine.HostedScript.LibraryLoader.CompileDelayedModules(ExternalLibraryDef library)
   at ScriptEngine.HostedScript.LibraryLoader.ProcessLibrary(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.ProcessLibrary(Library lib)
   at ScriptEngine.HostedScript.LibraryResolver.LoadLibraryInternal(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.LoadByPath(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.LoadByRelativePath(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.LoadLibrary(String value)
   at ScriptEngine.HostedScript.LibraryResolver.Resolve(String directive, String value, Boolean codeEntered)
   at ScriptEngine.Compiler.DirectiveMultiResolver.Resolve(String directive, String value, Boolean codeEntered)
   at ScriptEngine.CompilerService.ResolveDirective(String directive, String value, Boolean codeEntered)
   at ScriptEngine.Compiler.Compiler.HandleDirective()
   at ScriptEngine.Compiler.Compiler.HandleImportDirectives()
   at ScriptEngine.Compiler.Compiler.DispatchModuleBuild()
   at ScriptEngine.Compiler.Compiler.BuildModule()
   at ScriptEngine.Compiler.Compiler.Compile(ILexemGenerator lexer, ICompilerContext context)
   at ScriptEngine.CompilerService.CompileInternal(ICodeSource source)
   at ScriptEngine.CompilerService.Compile(ICodeSource source)
   at OneScript.WebHost.Application.ApplicationInstance.Create(ICodeSource src, IApplicationRuntime webApp) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Application/ApplicationInstance.cs:line 264
   at OneScript.WebHost.Infrastructure.AppStarter.CreateApp() in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Infrastructure/AppStarter.cs:line 72
   at OneScript.WebHost.Infrastructure.OneScriptServicePlugin.<>c.<InitializeScriptedLayer>b__4_0(IServiceProvider sp) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Infrastructure/OneScriptServicePlugin.cs:line 80
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OneScript.WebHost.Startup.StartOneScriptApp(IApplicationBuilder app, IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 108
   at OneScript.WebHost.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 98
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[5]
      Hosting shutdown
Unhandled exception. ScriptEngine.Compiler.SymbolNotFoundException: {Модуль /app/model/modules/ПодключенияКАгентам.os / Ошибка в строке: 34,37 / Неизвестный символ: ТипыОбъектовКластера}
        ПоляОбъекта = ТипыОбъектовКластера.СвойстваОбъекта(ТипОбъекта);
   at ScriptEngine.Compiler.CompilerContext.GetSymbol(String symbol, Func`2 extract)
   at ScriptEngine.Compiler.CompilerContext.GetVariable(String name)
   at ScriptEngine.Compiler.ModuleCompilerContext.GetVariable(String name)
   at ScriptEngine.Compiler.Compiler.BuildPushVariable(String identifier)
   at ScriptEngine.Compiler.Compiler.ProcessPrimaryIdentifier()
   at ScriptEngine.Compiler.Compiler.BuildPrimaryNode()
   at ScriptEngine.Compiler.Compiler.BuildExpression(Token stopToken)
   at ScriptEngine.Compiler.Compiler.BuildSimpleStatement()
   at ScriptEngine.Compiler.Compiler.BuildCodeBatch(Token[] endTokens)
   at ScriptEngine.Compiler.Compiler.DispatchMethodBody()
   at ScriptEngine.Compiler.Compiler.BuildSingleMethod()
   at ScriptEngine.Compiler.Compiler.DispatchModuleBuild()
   at ScriptEngine.Compiler.Compiler.BuildModule()
   at ScriptEngine.Compiler.Compiler.Compile(ILexemGenerator lexer, ICompilerContext context)
   at ScriptEngine.CompilerService.CompileInternal(ICodeSource source)
   at ScriptEngine.CompilerService.Compile(ICodeSource source)
   at ScriptEngine.Machine.Contexts.AttachedScriptsFactory.CompileModuleFromSource(CompilerService compiler, ICodeSource code, ExternalContextData externalContext)
   at ScriptEngine.HostedScript.LibraryLoader.CompileFile(String path)
   at ScriptEngine.HostedScript.LibraryLoader.<CompileDelayedModules>b__28_0(UserAddedScript moduleFile)
   at ScriptEngine.Utils.ForEach[T](IEnumerable`1 input, Action`1 action)
   at ScriptEngine.HostedScript.LibraryLoader.CompileDelayedModules(ExternalLibraryDef library)
   at ScriptEngine.HostedScript.LibraryLoader.ProcessLibrary(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.ProcessLibrary(Library lib)
   at ScriptEngine.HostedScript.LibraryResolver.LoadLibraryInternal(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.LoadByPath(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.LoadByRelativePath(String libraryPath)
   at ScriptEngine.HostedScript.LibraryResolver.LoadLibrary(String value)
   at ScriptEngine.HostedScript.LibraryResolver.Resolve(String directive, String value, Boolean codeEntered)
   at ScriptEngine.Compiler.DirectiveMultiResolver.Resolve(String directive, String value, Boolean codeEntered)
   at ScriptEngine.CompilerService.ResolveDirective(String directive, String value, Boolean codeEntered)
   at ScriptEngine.Compiler.Compiler.HandleDirective()
   at ScriptEngine.Compiler.Compiler.HandleImportDirectives()
   at ScriptEngine.Compiler.Compiler.DispatchModuleBuild()
   at ScriptEngine.Compiler.Compiler.BuildModule()
   at ScriptEngine.Compiler.Compiler.Compile(ILexemGenerator lexer, ICompilerContext context)
   at ScriptEngine.CompilerService.CompileInternal(ICodeSource source)
   at ScriptEngine.CompilerService.Compile(ICodeSource source)
   at OneScript.WebHost.Application.ApplicationInstance.Create(ICodeSource src, IApplicationRuntime webApp) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Application/ApplicationInstance.cs:line 264
   at OneScript.WebHost.Infrastructure.AppStarter.CreateApp() in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Infrastructure/AppStarter.cs:line 72
   at OneScript.WebHost.Infrastructure.OneScriptServicePlugin.<>c.<InitializeScriptedLayer>b__4_0(IServiceProvider sp) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Infrastructure/OneScriptServicePlugin.cs:line 80
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OneScript.WebHost.Startup.StartOneScriptApp(IApplicationBuilder app, IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 108
   at OneScript.WebHost.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 98
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at OneScript.WebHost.Program.Main(String[] args) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Program.cs:line 80

**Comment by howard180** [comment]
выше весь лог.

**Comment by arkuznetsov** [comment]
Попробуй в модуль "ПодключенияКАгентам.os" добавить в начале `#Использовать irac`

**Comment by howard180** [comment]
Помогло, теперь вот какая ошибка. 

`ScriptEngine.Machine.ExternalSystemException: {Модуль /app/model/modules/ОбщегоНазначения.os / Ошибка в строке: 14 / Внешнее исключение (System.Collections.Generic.KeyNotFoundException): The given key '/config/counters' was not present in the dictionary.}
        ПутьКМакету = ПолучитьМакет(ПутьКМакету);
`

**Comment by howard180** [comment]
Прошу прощения с последним разобрался: неправильно ConfigMap заполнил для counters.json.
Как проверю до конца - отпишу.

**Comment by howard180** [comment]
Все заработало.
